apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql.yaml

configMapGenerator:
- name: init-sql-configmap
  files:
  - init.sql

generatorOptions:
  disableNameSuffixHash: true
