apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-php-app
  labels:
    app: dummy-php-app
spec:
  selector:
    matchLabels:
      app: dummy-php-app
  template:
    metadata:
      labels:
        app: dummy-php-app
    spec:
      containers:
      - name: dummy-php-app
        image: dummy-php-app-image
        ports:
          - containerPort: 8000
        env:
          - name: MYSQL_HOST
            value: mysql-service
          - name: MYSQL_USER
            value: myUser
          - name: MYSQL_PASSWORD
            value: myPass
          - name: MYSQL_DATABASE
            value: php_with_tilt